### ISSUE TITLE
Options Chain command (options_chain) errors out while retrieving information

### ISSUE THREAD

**Issue by sher85** [Finnhub-Stock-API/finnhub-python#16]
while using the options.chain command in jupyter notebook, the code block displayed at the end of this issue errors out. In the error description, I can read the following

> FinnhubRequestException: FinnhubRequestException: Invalid Response:

 followed by the actual information I was requesting which is too lengthy to show here.
The code producing this error is this:

```
import finnhub
import os
finnhub_client = finnhub.Client(api_key=os.environ['FINNHUB_KEY'])

test = finnhub_client.option_chain(symbol='TSLA')
```

**Comment by KurtPrice** [comment]
I've been seeing the same issue. I'm not sure why this is happening. I'm going to look into a fix myself. My initial thoughts are that the validation on responses is incorrect and throwing this exception erroneously. Using the API documentation I was able to find https://finnhub.io/api/v1/stock/option-chain?symbol=TSLA which works without an API key in my browser. So in the mean time it may just be best to setup something with bs4 to grab the info from https.

If you have any ideas that are causing this issue, let me know here. I'd be excited to actually resolve this issue.

**Comment by KurtPrice** [comment]
Okay, so I figured out the root cause. It turns out that the api is returning the message without encoding. i.e. content-type = 'text/plain'. 

client.py:L52 with raise the exception that we see here. In the mean time you can add an if statement to handle this specific call. I have a hunch that this is the expected behavior by the client, and the real issue lies with the API not setting the content-type to be application/json.

I'll make a pull request either way to fix this.

**Comment by KurtPrice** [comment]
Pull request I mentioned above: https://github.com/Finnhub-Stock-API/finnhub-python/pull/18 @nongdenchet

**Comment by nongdenchet** [comment]
hey guys I have been busy recently. Let's me have a look

**Comment by nongdenchet** [comment]
Please upgrade your library to `2.2.1` to get the fix

**Comment by nongdenchet** [comment]
I have tested and confirmed that the issue is fixed for me. Thank you @KurtPrice
